### ISSUE TITLE
Italy flag: White stripe is too long

### ISSUE THREAD

**Issue by Jebble** [smucode/react-world-flags#206]
The white strip in the Italy flag is higher than the red and green stripes.

![image](https://user-images.githubusercontent.com/1397260/81916978-df4a1100-95d4-11ea-8342-a055d7a036b9.png)

**Comment by smucode** [comment]
Can you please elaborate, it looks the same to me?

**Comment by Jebble** [comment]
I can't elaborate more. The white stripe is 1px longer than the green and red stripes.

**Comment by smucode** [comment]
Right, I understand, you wrote "higher" in the initial message so i got confused.

So the italian flag is a SVG consisting of three equal sized rectangles. To render the vector (SVG) as pixels things like antialiasing come into play.

If you zoom into the image you posted, the transition from white to red looks fine, but the transition from green to white has a 1px blend of white and green. Since the width of the flag isn't divisible with 3, artifacts like this are to be expected.

Try setting `width` to something that is divisible with 3 - it should do the trick.

**Comment by Jebble** [comment]
I see, that actually makes sense! Thanks :)
