### ISSUE TITLE
why is gb.svg and us.svg larger ?

### ISSUE THREAD

**Issue by flazouh** [smucode/react-world-flags#672]
it gives a very undesired behaviour where this happens:
<img width="376" alt="Screenshot 2023-03-20 at 16 22 03" src="https://user-images.githubusercontent.com/25705704/226386801-006c6ccc-9ee4-4d5b-881f-12d70455ccff.png">

**Comment by smucode** [comment]
The flags have different proportions. Try setting a fixed width to resolve that: 

`<Flag code="nor" width="16" />`

Or better in your case since you probably already have a height set, create a wrapper element around the image with a fixed width just large enough for the widest image, so your name column aligns nicely.
